services:
  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"

  web-1:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./:/app
    command: node apps/web/server.js
    environment:
      INSTANCE_NAME: web-1

  web-2:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./:/app
    command: node apps/web/server.js
    environment:
      INSTANCE_NAME: web-2

  web-canary:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./:/app
    command: node apps/web/server.js
    environment:
      INSTANCE_NAME: web-canary

  scheduler:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./:/app
    command: sh -lc "npm install --no-audit --no-fund --silent && node apps/scheduler/scheduler.js"
    environment:
      AMQP_URL: amqp://rabbitmq:5672
      QUEUE_NAME: jobs.primary
      ROUTING_KEY: jobs.run
      DLX_NAME: jobs.dlx
    depends_on:
      - rabbitmq

  worker:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./:/app
    command: sh -lc "npm install --no-audit --no-fund --silent && node apps/worker/worker.js"
    environment:
      AMQP_URL: amqp://rabbitmq:5672
      QUEUE_NAME: jobs.primary
      DLQ_NAME: jobs.dead
      ROUTING_KEY: jobs.run
      DLX_NAME: jobs.dlx
      MAX_ATTEMPTS: 3
      FAIL_EVERY: 0
    depends_on:
      - rabbitmq

  nginx:
    image: nginx:1.27-alpine
    volumes:
      - ./infra/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./infra/nginx/certs:/etc/nginx/certs:ro
    ports:
      - "8443:443"
      - "8080:80"
    depends_on:
      - web-1
      - web-2
      - web-canary
      - scheduler
